parameters:
  Architecture: 'x64'

jobs:
- job: build_${{ parameters.Architecture }}
  displayName: Build Linux ${{ parameters.Architecture }}
  condition: succeeded()
  pool:
    type: linux
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - group: DotNetPrivateBuildAccess
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: repoRoot
    value: $(Build.SourcesDirectory)\ProjectMercury
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: true
  - name: ob_sdl_tsa_configFile
    value: $(repoRoot)\.config\tsaoptions.json
  - name: Architecture
    value: ${{ parameters.Architecture }}
  - name: Runtime
    value: 'linux-$(Architecture)'
  - name: ob_sdl_sbom_packageName
    value: 'AIShell.Linux.${{ parameters.Architecture }}'
  #CodeQL tasks added manually to workaround signing failures
  - name: ob_sdl_codeql_compiled_enabled
    value: false

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true

  - pwsh: |
      Get-ChildItem Env:
    displayName: Capture environment variables
    env:
      ob_restore_phase: true

  - template: /.pipelines/templates/update-nuget-config.yml@self
    parameters:
      repoRoot: $(repoRoot)

  # Add CodeQL Init task right before your 'Build' step.
  - task: CodeQL3000Init@0
    env:
      ob_restore_phase: true
    inputs:
      Enabled: true
      Language: csharp

  - pwsh: |
      Import-Module $(repoRoot)/build.psm1 -Force
      Install-Dotnet

      $runtime = '$(Runtime)'
      Write-Verbose "Building with Runtime: $runtime" -Verbose
      Start-Build -Runtime $runtime -Configuration Release -Clean -Verbose

      $outputJson = '$(repoRoot)/_build_output_.json'
      if (Test-Path $outputJson) {
        $result = Get-Content $outputJson | ConvertFrom-Json
        Write-Verbose "App path: $($result.App)" -Verbose
        Write-Verbose "Module path: $($result.Module)" -Verbose

        $vstsCommandString = "vso[task.setvariable variable=AppDir]$($result.App)"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"

        $vstsCommandString = "vso[task.setvariable variable=ModuleDir]$($result.Module)"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"
      }
    displayName: 'Build Linux - $(Architecture)'
    env:
      ob_restore_phase: true

  # Add CodeQL Finalize task right after your 'Build' step.
  - task: CodeQL3000Finalize@0
    env:
      ob_restore_phase: true

  - pwsh: |
      $uploadAppPath = New-Item -ItemType Directory -Path '$(ob_outputDirectory)/unsigned-app' -Force
      Write-Verbose -Verbose -Message "uploadAppPath: $uploadAppPath"
      Copy-Item -Path '$(AppDir)/*' -Destination $uploadAppPath -Recurse -Force -Verbose

      $uploadModulePath = New-Item -ItemType Directory -Path '$(ob_outputDirectory)/unsigned-module' -Force
      Write-Verbose -Verbose -Message "uploadModulePath: $uploadModulePath"
      Copy-Item -Path '$(ModuleDir)/*' -Destination $uploadModulePath -Recurse -Force -Verbose
    displayName: 'Upload unsigned app and module files'

  - template: /.pipelines/templates/finalize.yml@self

- job: sign_${{ parameters.Architecture }}
  displayName: Sign Linux ${{ parameters.Architecture }}
  condition: succeeded()
  dependsOn: build_${{ parameters.Architecture }}
  pool:
    type: windows
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - group: DotNetPrivateBuildAccess
  - group: certificate_logical_to_actual
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: repoRoot
    value: $(Build.SourcesDirectory)\ProjectMercury
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: false
  - name: ob_sdl_tsa_configFile
    value: $(repoRoot)\.config\tsaoptions.json
  - name: Architecture
    value: ${{ parameters.Architecture }}
  - name: Runtime
    value: 'linux-$(Architecture)'
  - name: ob_sdl_codeql_compiled_enabled
    value: false

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true

  - pwsh: |
      Get-ChildItem Env:
    displayName: Capture environment variables
    env:
      ob_restore_phase: true

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_linux_build_${{ parameters.Architecture }}
      path: $(Pipeline.Workspace)/drop_linux_build
    displayName: Download build

  - pwsh: |
      Get-ChildItem -Path $(Pipeline.Workspace)/drop_linux_build -Recurse
    displayName: 'List downloaded files'

  - template: /.pipelines/templates/sign-files.yml@self
    parameters:
      appPath: '$(Pipeline.Workspace)/drop_linux_build/unsigned-app'
      modulePath: '$(Pipeline.Workspace)/drop_linux_build/unsigned-module'
      repoRoot: '$(repoRoot)'

  - template: /.pipelines/templates/finalize.yml@self
