parameters:
  architecture: 'x64'

jobs:
- job: build_${{ parameters.architecture }}
  displayName: Build Linux ${{ parameters.architecture }}
  condition: succeeded()
  pool:
    type: linux
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_NOLOGO
    value: 1
  - group: DotNetPrivateBuildAccess
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: repoRoot
    value: $(Build.SourcesDirectory)\ProjectMercury
  - name: ob_sdl_sbom_enabled
    value: false
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: true
  - name: ob_sdl_tsa_configFile
    value: $(repoRoot)\.config\tsaoptions.json
  - name: Architecture
    value: ${{ parameters.architecture }}
  - name: Runtime
    value: 'linux-$(Architecture)'
  #CodeQL tasks added manually to workaround signing failures
  - name: ob_sdl_codeql_compiled_enabled
    value: false

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true

  - pwsh: |
      Get-ChildItem Env:
    displayName: Capture environment variables
    env:
      ob_restore_phase: true

  - template: /.pipelines/templates/update-nuget-config.yml@self
    parameters:
      repoRoot: $(repoRoot)

  # Add CodeQL Init task right before your 'Build' step.
  - task: CodeQL3000Init@0
    env:
      ob_restore_phase: true
    inputs:
      Enabled: true
      Language: csharp

  - pwsh: |
      Import-Module $(repoRoot)/build.psm1 -Force
      Install-Dotnet

      $runtime = '$(Runtime)'
      Write-Verbose "Building with Runtime: $runtime" -Verbose
      Start-Build -Runtime $runtime -Configuration Release -Clean -NotIncludeModule -Verbose

      $outputJson = '$(repoRoot)/_build_output_.json'
      if (Test-Path $outputJson) {
        $result = Get-Content $outputJson | ConvertFrom-Json
        Write-Verbose "App path: $($result.App)" -Verbose

        $vstsCommandString = "vso[task.setvariable variable=AppDir]$($result.App)"
        Write-Host ("sending " + $vstsCommandString)
        Write-Host "##$vstsCommandString"
      }
    displayName: 'Build Linux - $(Architecture)'
    env:
      ob_restore_phase: true

  # Add CodeQL Finalize task right after your 'Build' step.
  - task: CodeQL3000Finalize@0
    env:
      ob_restore_phase: true

  - pwsh: |
      Get-ChildItem $(AppDir) -Recurse
    displayName: "List AIShell app files"
    env:
      ob_restore_phase: true

  - task: CopyFiles@2
    displayName: "Upload unsigned app files"
    env:
      ob_restore_phase: true
    inputs:
      SourceFolder: $(AppDir)
      Contents: '**/*'
      TargetFolder: $(ob_outputDirectory)

  - template: /.pipelines/templates/finalize.yml@self

- job: sign_${{ parameters.architecture }}
  displayName: Sign Linux ${{ parameters.architecture }}
  condition: succeeded()
  dependsOn: build_${{ parameters.architecture }}
  pool:
    type: windows
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_NOLOGO
    value: 1
  - group: DotNetPrivateBuildAccess
  - group: certificate_logical_to_actual
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: repoRoot
    value: $(Build.SourcesDirectory)\ProjectMercury
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: false
  - name: ob_sdl_tsa_configFile
    value: $(repoRoot)\.config\tsaoptions.json
  - name: Architecture
    value: ${{ parameters.architecture }}
  - name: Runtime
    value: 'linux-$(Architecture)'
  - name: ob_sdl_codeql_compiled_enabled
    value: false
  - name: ob_sdl_sbom_packageName
    value: 'AIShell.Linux.$(Architecture)'

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true

  - pwsh: |
      Get-ChildItem Env:
    displayName: Capture environment variables
    env:
      ob_restore_phase: true

  - template: /.pipelines/templates/update-nuget-config.yml@self
    parameters:
      repoRoot: $(repoRoot)

  - pwsh: |
      Import-Module $(repoRoot)/build.psm1 -Force
      Install-Dotnet
      Start-Build -Configuration Release -Clean -NotIncludeModule -Verbose
    displayName: 'Build again to get correct SBOM'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_linux_build_$(Architecture)
      path: $(Pipeline.Workspace)/drop_linux_build
    displayName: Download build

  - pwsh: |
      Get-ChildItem -Path $(Pipeline.Workspace)/drop_linux_build -Recurse
    displayName: 'List downloaded files'

  - template: /.pipelines/templates/sign-files.yml@self
    parameters:
      appPath: '$(Pipeline.Workspace)/drop_linux_build'
      repoRoot: '$(repoRoot)'

  - template: /.pipelines/templates/finalize.yml@self
